<%
	session("user_id")=""
	session("user_name")=""
	session("user_pass")=""
	session("user_nationality")=""
	session("real_name")=""
	session("user_identity")=""
	session("user_sex")=""
	session("user_inhabit")=""
	session("user_degree")=""
	session("user_birthday")=""
	session("user_trade")=""
	session("user_career")=""
	session("user_liking")=""
	session("user_plan")=""
	session("user_habitus")=""
	session("user_phone")=""
	session("user_move")=""
	session("user_email")=""
	session("user_address")=""
	session("auth_id")=""
	
	session("com_id")=""
	session("com_name")=""
	session("com_pass")=""
	session("com_trademark")=""
	session("com_trade")=""
	session("com_bond")=""
	session("com_address")=""
	session("com_phone1")=""
	session("com_phone2")=""
	session("com_fax")=""
	session("com_www")=""
	session("com_email")=""
	session("auth_id")=""
	
	response.Redirect "index.asp"
%>